= Overview

Conformance testing is used as the basis of product certification, and has the following goals:

* _Tendering_: enable tendering authorities to state formal criteria for compliance in tenders
* _Protection for solution developers_: enables bona fide vendors and other developers to prove the quality of their solutions compared to other offerings claiming conformance
* _Protection for procurement_: provides a way of ensuring that purchased solutions can be contractually guaranteed to perform in certain ways

== Scope

This specification describes the _conformance points_ for _openEHR platform systems_ whose semantics are specified by the openEHR Foundation. Such systems typically include data services (i.e. persistence & querying) along with various options dependent on the orientation of the product and its maturity; these may include integration capabilities, domain services (e.g. guidelines, planning) and so on.

A conformance point is understood as a _testable capability of a system that relates to a business-relevant capability_. For example, conformance points for an EHR persistence service (aka Clinical Data Repository, or CDR) may include 'create EHR', 'update EHR', 'versioning' etc.

One or more methods of testing each conformance point is described in this specification. Conformance testing is based on comparing system behaviour and data to the relevant openEHR published specifications.

Fine-grained system capabilities naturally aggregate in various ways to produce specific coarse-grained business-relevant profiles, such as for a 'minimally viable openEHR system' and so on. In order to provide the customer side with a means of determining what constitute sensible sets of requirements, the specification defines a set of _profiles_.

The scope of this specification is limited to the following:

* (specific) functional capabilities of systems;
* limited non-functional capabilities, including:
** external data format used by exposed APIs;
** Security and Privacy.

The system being tested is accessed via various openEHR REST APIs which must be minimally implemented i.e. sufficiently for the test cases to be exercised.

This specification does not cover claims to other non-functional characteristics such as capacity, performance, availability, or consistency of systems. It is however recommended that supply agreements for operational solutions include criteria for these factors, as relevant to the situation. As a guide, the following criteria should be considered:

* *Capacity*: capacity of system in terms of:
** _data volume_: 
*** number of active EHRs supported for a given reported latency;
*** number of archived EHRs supported;
** _user load_:
*** number of concurrent committers for a given reported latency;
*** number of concurrent readers for a given reported latency;
* *Performance*: tested performance of system in terms of reported transaction processing rates;
* *Availability*: tested latency of system with respect to standard queries over time.

It may be possible to develop a band-based rating sytem for capacity. Performance, availability, consistency and related characteristics may be assessed using a framework that takes account of the CAP and / or PACELC theorems.

Specific applications are also outside the scope of this specification, however, it is assumed that in order for solutions to be testable, a minimal generic viewing tool is provided to enable viewing or data and other testable events.

== Conformance Certificate

An openEHR Conformance Certificate consists of a rating in the Functional and Content dimensions, and a detailed report. The ratings are as follows:

[cols="2,1,4", options="header"]
|===
|Characteristics            |Levels			|Description

.3+|*Functional*            |CORE			|Core functionality required for operational deployment.
                            |STANDARD       |More comprehensive capabilities useful in a 'standard' EHR operational environment.
                            |Extras     	|Extra features required in specific circumstances.

.2+|*Security and privacy*  |xxx            |xxx
                            |xxx            |xx
                    
.2+|*External data format*  |Canonical XML  |openEHR Canonical XML, defined by published XSDs
                            |Canonical JSON |openEHR Canonical XML, defined by published transform of XML

|===

An awarded certificate for a typical system will look as follows:

------
openEHR Conformance Certificate
===============================

Solution:       BestEHR release 2.4
                details ...
Vendor:         ACME EHR systems LLC, Maxperformancia
Assessor:       openEHR Foundation
Infrastructure: openEHR CNF-test WS 1.5.0 on AWS ...
                System under test on AWS ...
Date:           12 April 2017
    
Certified conformance
=====================
Functional:     CORE, Extras
Sec & Priv:     xxx
Ext Data Fmt:   XML, JSON


Detailed Report
===============

+================+===================+================+====================+==============+===========+
|SUT Component   |Product Component  |Capability      |Conformance point   |Tests         |           |
+================+===================+================+====================+==============+===========+
|ACME CDR        |EHR persistence    |Versioning      |Contribution commit |EHR-VER-01    |pass       |
|                |                   |                |new                 |EHR-VER-02    |pass       |
|                |                   |                |                    |EHR-VER-03    |FAIL       |
|                |                   |                +--------------------+--------------+-----------+
|                |                   |                |Contribution commit |EHR-VER-09    |pass       |
|                |                   |                |changed             |EHR-VER-11    |pass       |
+----------------+-------------------+----------------+--------------------+--------------+-----------+
|                                         ....                                            |           |
+----------------+-------------------+----------------+--------------------+--------------+-----------+
|etc             |etc                |etc             |etc                 |etc           |           |
+----------------+-------------------+----------------+--------------------+--------------+-----------+

------


