= Conformance Schedule

== Overview

The following table shows the schedule according to which functional conformance claims can be made for a solution.

=== Understanding the conformance tables

[cols="2,3,3,3,3", options="header"]
|===
|Product +
 Component
                |Capability             |Conformance Point          |Access method             |Test script
                
|Component offered +
 in proposed system
                |Claimed capability +
                 of the component       |Testable characteristic +
                                         within this capability     |Method of communicating +
                                                                     with component             |Logical structure of +
                                                                                                 Test Case
|===


== Conformance Test Tables

=== Data Persistence Components

[cols="2,3,3,3,3", options="header"]
|===
|Product +
 Component
                |Capability         |Conformance Point      |Access method             |Test script

.26+|*EHR +
    Persistence*
             .3+|*OPT 1.4*          |Load templates         |DEFINITIONS API            |API:upload opt14 template * N; +
                                                                                         API:list opt14 templates
                                    |Get template by id     |DEFINITIONS API            |API:get opt14 template by id

                                    |Get archetypes used    |DEFINITIONS API            |API:

            .11+|*EHR data*  +
                 +
                 (specs: +
                 {openehr_rm_ehr}[EHR IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                    |Create EHR             |EHR API                    |API:create ehr; +
                                                                                         API:get ehr

                                    |Get EHR status         |EHR API             		|API:get ehr_status

                                    |Update EHR status      |EHR API             		|API:update ehr_status; +
                                                                                         API:get ehr_status; +
                                                                                         regression diff
                                     
                                    |Create COMPOSITION +
                                     change set             |EHR API           			|API:create contribution; +
                                                                                         COMP:get composition; +
                                                                                         regression diff

                                    |Update COMPOSITION +
                                     change set             |EHR API           			|API:create contribution; +
                                                                                         COMP:get composition; +
                                                                                         regression diff
                                    |Create + 
                                     COMPOSITION            |EHR API            		|API:create composition; +
                                                                                         API:get composition; +
                                                                                         regression diff
                                    |Retrieve + 
                                     COMPOSITION            |EHR API            		|API:update composition; +
                                                                                         API:get composition; +
                                                                                         regression diff
                                    |Update + 
                                     COMPOSITION            |EHR API            		|API:update composition; +
                                                                                         API:get composition; +
                                                                                         regression diff
                                    |Delete + 
                                     COMPOSITION            |EHR API            		|API:create composition; +
                                                                                         API:delete composition; +
                                                                                         API:get composition (fail)
                                    |Create directory +
                                     (FOLDERs)              |EHR API              		|API:create directory; +
                                                                                         API:get directory; +
                                                                                         regression diff
                                    |Update directory +
                                     (FOLDERs)              |EHR API              		|API:update directory; +
                                                                                         API:get directory; +
                                                                                         regression diff

             .6+|*Versioning* +
                 +
                 (specs: +
                 {openehr_rm_common}#_change_control_package[Versioning])
                                    |Get EHR_STATUS version |EHR API             		|API:get ehr_status version; +
                                                                                         API:update ehr_status; +
                                                                                         API:get ehr_status version (prev); +
                                                                                         regression diff
                                                                                         
                                    |Get EHR_STATUS version +
                                     by id                  |EHR API             		|API:get versioned_ehr_status; +
                                                                                         API:get ehr_status version by uid; +
                                                                                         regression diff

                                    |Get EHR_STATUS version +
                                     at time                |EHR API             		|API:get versioned_ehr_status; +
                                                                                         API:get ehr_status version at time; +
                                                                                         regression diff

                                    |Get COMPOSITION version +
                                     by id                  |EHR API            		|API:get composition version; +
                                                                                         API:update composition; +
                                                                                         API:get composition version (prev); +
                                                                                         regression diff

                                    |Get COMPOSITION version +
                                     at time                |EHR API            		|API:get versioned_composition; +
                                                                                         API:get composition version at time; +
                                                                                         regression diff

                                    |List CONTRIBUTIONs     |EHR API                    |API:update xxx * N; +
                                                                                         API:list contributions

             .3+|*Archetype +
                 validation*        |Accept valid content   |EHR API                    |xxx
                 
                                    |Reject invalid archetype
                                                            |EHR API                    |xxx
                                     
                                    |Reject invalid content
                                                            |EHR API                    |xxx

             .3+|*Logging* +
                 +
                 (specs: +
                 XXXX)
                                    |Log creates            |EHR API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API create call; +
                                                                                         check sys log
                                    |Log updates            |EHR API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API commit call; +
                                                                                         check sys log
                                    |Log reads              |EHR API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API retrieve call; +
                                                                                         check sys log
                                            
.10+|*Demographic +
 Persistence*
             .3+|*Demographic data*  +
                 +
                 (specs: +
                 {openehr_rm_demographic}[Demographic IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                    |Create Party           |Demographic API            |API:create party; +
                                                                                         API:retrieve party; +
                                                                                         regression diff
                                                                                         
                                    |Update PARTY           |Demographic API            |API:create party; +
                                                                                         API:retrieve party; +
                                                                                         API:update party; +
                                                                                         API:retrieve party; +
                                                                                         regression diff

                                    |Retrieve PARTY         |Demographic API            |xxx

                |*Versioning* +
                 +
                 (specs: +
                 {openehr_rm_common}#_change_control_package[Versioning])
                                    |Commit Party group +
                                     change set             |Demographic API            |xxx

             .3+|*Archetype +
                 validation*        |Accept valid content   |Demographic API            |API create call; +
                                                                                         check sys log
                                    |Reject invalid +
                                    archetype               |Demographic API            |API create call; +
                                                                                         check sys log

                                    |Reject invalid content |Demographic API            |API create call; +
                                                                                         check sys log
             .3+|*Logging*  +
                 +
                 (specs: +
                 XXXX)
                                    |Log creates            |Demographic API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API create call; +
                                                                                         check sys log
                                    |Log updates            |Demographic API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API commit call; +
                                                                                         check sys log
                                    |Log reads              |Demographic API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API retrieve call; +
                                                                                         check sys log

|===

[.tbd]
TODO: In theory we could include Integration Entries ({openehr_rm_integration}[Integration IM]), but I don't think anyone uses them. I suspect that spec should be retired.

=== Integration Components

[cols="2,3,3,3,3", options="header"]
|===
|Product +
 Component
                |Capability             |Conformance Point      |Access method             |Test script
                
.6+|*Messaging* 
             .5+|*EHR Extract* +
                 +
                 (specs: +
                 {openehr_rm_ehr_extract}[EHR Extract IM] +
                 {openehr_rm_ehr}[EHR IM] +
                 {openehr_rm_demographic}[Demographic IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                        |Export openEHR Extract +
                                         1 patient              |EHR_EXTRACT API           |???
                                         
                                        |Export openEHR Extract +
                                         w/ versions            |EHR_EXTRACT API           |???
                                         
                                        |Export openEHR Extract +
                                         multiple patients      |EHR_EXTRACT API           |???
                                         
                                        |Export generic Extract +
                                         1 patient              |EHR_EXTRACT API           |???
                                         
                                        |Export whole +
                                         patient record         |EHR_EXTRACT API           |???
                 
                |*Template Data +
                 Schema (TDS)*          |TDD commit             |TDD API                   |???
                 
|===


=== Other Components

[cols="2,3,3,3,3", options="header"]
|===
|Product +
 Component
                |Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.7+|*Querying* +
 +
 (specs: +
 {openehr_query_aql}[AQL specification])
             .2+|*Stored queries*   |Store query            |DEFINITIONS API        |API:create stored query; +
                                                                                     API:get stored query; +
                                                                                     API:list stored queries
                                                                                     
                					|Delete query           |DEFINITIONS API        |API:create stored query; +
                                                                                     API:delete stored query; +
                                                                                     API:get stored query; +
                                                                                     API:list stored queries
                                                                                     
                |*AQL basic*        |Patient-centric        |QUERY API              |EHR:commit composition x N; +
                                                                                     API:execute ad hoc query +
                                                                                     regression.
                                                                                     
             .2+|*AQL advanced*     |Patient-centric        |QUERY API              |EHR:commit composition x N; +
                                                                                     AQL:create stored query; +
                                                                                     API:execute stored query; +
                                                                                     API:execute ad hoc query; +
                                                                                     regression.
                                                                                     
                                    |Population query       |QUERY API              |EHR:commit composition x N; +
                                                                                     AQL:create stored query; +
                                                                                     API:execute stored query; +
                                                                                     API:execute ad hoc query; +
                                                                                     regression.
             .2+|*AQL + + 
                 terminology*       |Patient-centric        |QUERY API              |EHR:commit composition x N; +
                                                                                     AQL:create stored query; +
                                                                                     API:execute stored query; +
                                                                                     API:execute ad hoc query; +
                                                                                     regression.
                                                                                     
                                    |Population query       |QUERY API              |EHR:commit composition x N; +
                                                                                     AQL:create stored query; +
                                                                                     API:execute stored query; +
                                                                                     API:execute ad hoc query; +
                                                                                     regression.
                                                                                     
.8+|*ADMIN*     |*List transactions*|List CONTRIBUTIONs +
                                     since time             |ADMIN API              |API:
             .2+|*Transaction +
                 statistics*        |Get CONTRIBUTION +
                                     count since time       |ADMIN API              |API:

                                    |Get COMPOSITIONs +
                                     add/mod/del +
                                     since time             |ADMIN API              |API:

                |*Bulk EHR Export*  |Export all EHRs        |ADMIN API              |EHR:create EHR x N; + ;
                                                                                     EHR:commit composition x N; + 
                                                                                     API:export; +
                                                                                     file test / diff
                                                                                     
                |*Bulk EHR Load*    |Load complete file     |ADMIN API              |API:load; +
                                                                                     API:retrieve x N
                |*Archive EHRs*     |Archive EHRs by +
                                     identifier             |ADMIN API              |API:archive; +
                                                                                     review archive;
                                                                                     confirm status on +
                                                                                     archived EHRs
                |*Physical EHR +
				 delete*     		|Delete EHR by +
                                     identifier             |ADMIN API              |API:delete_ehr
                |*Physical +
                 Demographics +
				 delete*     		|Delete PARTY by +
                                     identifier             |ADMIN API              |API:delete_party
|===

=== APIs

[cols="2,3,3,3,3", options="header"]
|===
|Product +
 Component
                |Capability        |Conformance +
                                    point                   |Access Method          |Test Script
                
.7+|*REST APIs* |*DEFINITIONS API* |???                     |DEFINITIONS API        |Exercise all functions +
                                                                                     & arguments

                |*EHR API*         |???                     |EHR API                |Exercise all functions +
                                                                                     & arguments
                                                                                     
                |*DEMOGRAPHIC API* |???                     |DEMOGRAPHIC API        |Exercise all functions +
                                                                                     & arguments
                                                                                     
                |*QUERY API*       |???                     |QUERY API              |Exercise all functions +
                                                                                     & arguments
                                                                                         
                |*CDS API*         |???                     |CDS API                |Exercise functions +
                                                                                     & arguments
                                                                                         
                |*ADMIN API*       |???                     |ADMIN API              |Exercise functions +
                                                                                     & arguments
                                                                                         
                |*TDD API*         |???                     |TDD API                |Exercise functions +
                                                                                     & arguments
|===

=== Non-Functional Characteristics

[cols="2,3,3,3,3", options="header"]
|===
|Product Attribute
                |Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.3+|*Security & +
 Privacy*
                |*Signing*  +
                 +
                 (specs: +
                 {openehr_rm_common}#_digital_signature[Digital Signature])
                                    |???                    |xxx API                |Commit/Retrieve +
                                                                                     data regression
                |*Anonymous EHRs*  +
                 +
                 (specs: +
                 {openehr_overview}#_overview_4[EHR/Demographic separation])
                                    |???                    |EHR API                |Commit/query
                |*Info Consent*  +
                 +
                 (specs: +
                 ???)
                                    |???                    |xxx API                |Commit/Retrieve +
                                                                                     data regression
|===

=== Tools

Tools supplied with an openEHR EHR solution should include:

* generic EHR viewer - a generic web portal for viewing EHR data in generic form.

