= Conformance Schedule

== Overview

The following table shows the schedule according to which functional conformance claims can be made for a solution.

=== Understanding the conformance tables

[cols="2,2,2,2,2", options="header"]
|===
|Product Component
                |Capability             |Conformance Point          |Access method             |Test script
                
|Component offered +
 in proposed system
                |Claimed capability +
                 of the component       |Testable characteristic +
                                         within this capability     |Method of communicating +
                                                                     with component             |Logical structure of +
                                                                                                 Test Case
|===


== Conformance Test Tables

=== Data Persistence Components

[cols="2,2,2,2,2", options="header"]
|===
|Product Component
                |Capability         |Conformance Point      |Access method             |Test script

.26+|*EHR +
    Persistence*
             .3+|*OPT 1.4*          |Load templates         |MODELS API                 |API:upload opt14 template * N; +
                                                                                         API:list opt14 templates
                                    |Get template by id     |MODELS API                 |API:get opt14 template by id

                                    |Get archetypes used    |MODELS API                 |API:

            .10+|*EHR data*  +
                 +
                 (specs: +
                 {openehr_rm_ehr}[EHR IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                    |Create EHR             |EHR API                    |API:create ehr; +
                                                                                         API:get ehr

                                    |Get EHR status         |EHR_STATUS API             |API:get ehr_status

                                    |Update EHR status      |EHR_STATUS API             |API:update ehr_status; +
                                                                                         API:get ehr_status; +
                                                                                         regression diff
                                     
                                    |Create COMPOSITIONs    |CONTRIBUTION API           |API:create contribution; +
                                                                                         API:get contribution; +
                                                                                         regression diff

                                    |Update COMPOSITIONs    |CONTRIBUTION API           |API commit call; +
                                                                                         API retrieve call; +
                                                                                         regression diff
                                    |Create + 
                                     COMPOSITION            |COMPOSITION API            |API:create composition; +
                                                                                         API:get composition; +
                                                                                         regression diff
                                    |Retrieve + 
                                     COMPOSITION            |COMPOSITION API            |API:update composition; +
                                                                                         API:get composition; +
                                                                                         regression diff
                                    |Update + 
                                     COMPOSITION            |COMPOSITION API            |API:update composition; +
                                                                                         API:get composition; +
                                                                                         regression diff
                                    |Create directory +
                                     (FOLDERs)              |DIRECTORY API              |API:create directory; +
                                                                                         API:get directory; +
                                                                                         regression diff
                                    |Update directory +
                                     (FOLDERs)              |DIRECTORY API              |API:update directory; +
                                                                                         API:get directory; +
                                                                                         regression diff

             .7+|*Versioning* +
                 +
                 (specs: +
                 {openehr_rm_common}#_change_control_package[Versioning])
                                    |Get EHR_STATUS version |EHR_STATUS API             |API:get ehr_status version; +
                                                                                         API:update ehr_status; +
                                                                                         API:get ehr_status version (prev); +
                                                                                         regression diff
                                                                                         
                                    |Get EHR_STATUS version +
                                     at time                |EHR_STATUS API             |API:get versioned_ehr_status; +
                                                                                         API:get ehr_status version at time; +
                                                                                         regression diff

                                    |Get EHR_STATUS version +
                                     by id                  |EHR_STATUS API             |API:get versioned_ehr_status; +
                                                                                         API:get ehr_status version by uid; +
                                                                                         regression diff

                                    |Get COMPOSITION version|COMPOSITION API            |API:get composition version; +
                                                                                         API:update composition; +
                                                                                         API:get composition version (prev); +
                                                                                         regression diff

                                    |Get COMPOSITION version +
                                     at time                |COMPOSITION API            |API:get versioned_composition; +
                                                                                         API:get composition version at time; +
                                                                                         regression diff

                                    |Get COMPOSITION version +
                                     by id                  |COMPOSITION API            |API:get versioned_composition; +
                                                                                         API:get composition version by uid; +
                                                                                         regression diff

                                    |List CONTRIBUTIONs     |EHR API                    |API:update xxx * N; +
                                                                                         API:list contributions

             .3+|*Archetype +
                 validation*        |Accept valid content   |EHR API                    |xxx
                                    |Reject invalid archetype |EHR API                  |xxx
                                    |Reject invalid content |EHR API                    |xxx

             .3+|*Logging* +
                 +
                 (specs: +
                 openEHR IHE ATNA Profile)
                                    |Log creates            |EHR API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API create call; +
                                                                                         check sys log
                                    |Log updates            |EHR API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API commit call; +
                                                                                         check sys log
                                    |Log reads              |EHR API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API retrieve call; +
                                                                                         check sys log
                                            
.11+|*Demographic +
 Persistence*
             .4+|*Demographic data*  +
                 +
                 (specs: +
                 {openehr_rm_demographic}[Demographic IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                    |Create Party           |Demographic API            |xxx
                                    |Update PARTY           |Demographic API            |xxx
                                    |Retrieve PARTY         |Demographic API            |xxx
                                    |Create/Retrieve +
                                     PARTY group            |Demographic API            |xxx

                |*Versioning* +
                 +
                 (specs: +
                 {openehr_rm_common}#_change_control_package[Versioning])
                                    |Contribution commit    |Demographic API or +
                                                             generic viewer             |xxx

             .3+|*Archetype +
                 validation*        |Accept valid content   |Demographic API            |API create call; +
                                                                                         check sys log
                                    |Reject invalid +
                                    archetype               |Demographic API            |API create call; +
                                                                                         check sys log

                                    |Reject invalid content |Demographic API            |API create call; +
                                                                                         check sys log
             .3+|*Logging*  +
                 +
                 (specs: +
                 openEHR IHE ATNA Profile)
                                    |Log creates            |Demographic API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API create call; +
                                                                                         check sys log
                                    |Log updates            |Demographic API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API commit call; +
                                                                                         check sys log
                                    |Log reads              |Demographic API, +
                                                             SYSLOG API / +
                                                             sys log viewer             |API retrieve call; +
                                                                                         check sys log

|===

[.tbd]
TODO: In theory we could include Integration Entries ({openehr_rm_integration}[Integration IM]), but I don't think anyone uses them. I suspect that spec should be retired.

=== Integration Components

[cols="2,2,2,2,2", options="header"]
|===
|Product Component
                |Capability             |Conformance Point      |Access method             |Test script
                
.6+|*Messaging* 
             .5+|*EHR Extract* +
                 +
                 (specs: +
                 {openehr_rm_ehr_extract}[EHR Extract IM] +
                 {openehr_rm_ehr}[EHR IM] +
                 {openehr_rm_demographic}[Demographic IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                        |Export openEHR Extract +
                                         1 patient              |EHR_EXTRACT API           |???
                                        |Export openEHR Extract +
                                         w/ versions            |EHR_EXTRACT API           |???
                                        |Export openEHR Extract +
                                         multiple patients      |EHR_EXTRACT API           |???
                                        |Export generic Extract +
                                         1 patient              |EHR_EXTRACT API           |???
                                        |Export whole +
                                         patient record         |EHR_EXTRACT API           |???
                 
                |*Template Data +
                 Schema (TDS)*          |TDD commit             |TDD API                    |???
                 
|===


=== Other Components

[cols="2,2,2,2,2", options="header"]
|===
|Product Component
                |Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.5+|*Querying* +
 +
 (specs: +
 {openehr_query_aql}[AQL specification])
                |*AQL basic*        |Patient-centric        |AQL API                |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
                                                                                     
             .2+|*AQL advanced*     |Patient-centric        |AQL API                |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
                                                                                     
                                    |Population query       |AQL API                |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
             .2+|*AQL + + 
                 terminology*       |Patient-centric        |AQL API                |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
                                                                                     
                                    |Population query       |AQL API                |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
                                                                                     
.6+|*CDR*       |*List transations* |List CONTRIBUTIONs +
                                     since time             |CDR API                |API:
             .2+|*transaction +
                 statistics*        |Get CONTRIBUTION +
                                     count since time       |CDR API                |API:

                                    |Get COMPOSITIONs +
                                     add/mod/del +
                                     since time             |CDR API                |API:

                |*Bulk EHR Export*  |Export all EHRs        |CDR API                |API commit calls; + 
                                                                                     API dump call; +
                                                                                     file test / diff
                                                                                     
                |*Bulk EHR Load*    |Load complete file     |CDR API                |API load call; +
                                                                                     API retrieve calls
                |*Archive EHRs*     |Archive EHRs by +
                                     identifier             |CDR API                |API archive call; +
                                                                                     review archive;
                                                                                     confirm status on +
                                                                                     archived EHRs
|===

=== APIs

[cols="2,2,2,2,2", options="header"]
|===
|Product Component
                |Capability             |Conformance +
                                         point                  |Access Method          |Test Script
                
.10+|*APIs*     |*MODELS REST API*      |???                    |MODELS API             |xxx
                |*EHR REST API*         |???                    |EHR API                |Exercise all functions +
                                                                                         & arguments
                |*EHR_STATUS +
                 REST API*              |???                    |EHR_STATUS API         |Exercise all functions +
                                                                                         & arguments
                |*CONTRIBUTION +
                 REST API*              |???                    |CONTRIBUTION API       |Exercise all functions +
                                                                                         & arguments
                |*COMPOSITION +
                 REST API*              |???                    |COMPOSITION API        |Exercise all functions +
                                                                                         & arguments
                |*DIRECTORY +
                 REST API*              |???                    |DIRECTORY API          |Exercise all functions +
                                                                                         & arguments
                |*QUERY REST API*       |???                    |QUERY API              |Exercise all functions +
                                                                                         & arguments
                |*CDS REST API*         |???                    |CDS API                |Exercise functions +
                                                                                         & arguments
                |*CDR REST API*         |???                    |CDR API                |Exercise functions +
                                                                                         & arguments
                |*TDD REST API*         |???                    |TDD API                |Exercise functions +
                                                                                         & arguments
|===

=== Non-Functional Characteristics

[cols="2,2,2,2,2", options="header"]
|===
|Product Attribute
                |Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.3+|*Security & +
 Privacy*
                |*Signing*  +
                 +
                 (specs: +
                 {openehr_rm_common}#_digital_signature[Digital Signature])
                                    |???                    |xxx API                |Commit/Retrieve +
                                                                                     data regression
                |*Anonymous EHRs*  +
                 +
                 (specs: +
                 {openehr_overview}#_overview_4[EHR/Demographic separation])
                                    |???                    |EHR API                |Commit/query
                |*Info Consent*  +
                 +
                 (specs: +
                 ???)
                                    |???                    |xxx API                |Commit/Retrieve +
                                                                                     data regression
|===

=== Tools

Tools supplied with an openEHR EHR solution should include:

* generic EHR viewer - a generic web portal for viewing EHR data in generic form.

