= Evaluation Environment

Conformance evaluation relies on some normative idea of systems that may be tested against a set of specifications on which they claim to be based. This section describes the assumptions that are made about systems that may be reasonably tested according to this conformance specification.

== System Under Test (SUT)

It is assumed that any system provided to be tested for conformance according to this specification is of a platform nature, i.e. consisting of one or more _product components_ that are exposed via corresponding _services_, and that the components are based on published openEHR specifications. Consequently, certain types of components are assumed and named in this specification, e.g. 'EHR persistence', 'Demographic persistence', 'Querying' and so on. 

The functionality assumed to be in these components is indirectly defined by the openEHR REST APIs, of which the {openehr_ehr_rest_api}[openEHR EHR REST API] is the primary, and directly defined by the openEHR specifications designated as relevant to each call. For this reason, the openEHR REST APIs are assumed to be implemented by the system to a sufficient extent for performing the tests (i.e. not all calls in the full REST API are required for the conformance testing described here.) Which calls are required is indicated in the Conformance Schedule below.

The openEHR REST APIs handle data in two ways: canonical openEHR XML, based on published XML schemas (XSDs), and a JSON equivalent, which is defined as a standard transform of openEHR object structures. The providers of the SUT may opt for either format, and are only _required_ to implement one.

[.tbd]
ISSUE: where defined, details?

A further assumption about an openEHR platform is that it writes to an IHE ATNA-based System Log service, which may be external or part of the product, and if it exists, it is accessible in the test environment via an appropriate interface.

Lastly it is assumed that there may be a _generic data viewer_ available, i.e. a web application that be used in a normal brower that enables the data and other state in the principal services to be viewed in a generic way.

The following figure illustrates the notional openEHR Platform assumed in any SUT.

[.text-center]
.Assumed openEHR Platform
image::diagrams/openEHR_platform_conformance.svg[id=openehr_platform_conformance, align="center", width=50%]

In the above, elements with solid outlines are required, while elements with dashed outlines are those that may or may not be part of a given product. The generic portal is not considered part of the system under test, but an additional tool available to facilitate testing. Any actual system under test will normally consist of the mandatory parts plus one or more other components germane to the intended product function.

== Manual Testing

TBD

== Automated Testing

Automated conformance testing is performed by the interaction of the openEHR CNF-test web service with a system under test. A test configuration indicates which conformance claims are to be tested (e.g. functional=CORE; content=STANDARD+Extra), and appropriate sets of tests are executed. The result is a detailed test report, together with the highest conformance levels reached in the requested categories.
