== openEHR Conformance Testing Specification

[width="100%",cols="^43%,^15%,^42%",options="header",]
|===
|Author |Version |Comments
|Pablo Pazos Gutierrez pablo.pazos@cabolabs.com |1.0 (2021-04-14) |First
version integrating all tests suites into a single documenation.
|===

== Index

* link:#introduction[Introduction]
* link:#general-considerations[General considerations]
** link:#preconditions[Preconditions]
** link:#considerations[Considerations]
* link:#test-suites[Test Suites]
** link:#test-suite-components[Test Suite Components]
*** link:#knowledge[Knowledge]
*** link:#ehr[EHR]
*** link:#ehrcomposition[EHR/COMPOSITION]
*** link:#ehrcontribution[EHR/CONTRIBUTION]
*** link:#directory[DIRECTORY]
** link:#test-case-dependencies[Test Case Dependencies]

== Introduction

This documentation contains different test suites focused on validating
any implementation of the
https://specifications.openehr.org/releases/SM/latest/openehr_platform.html[openEHR
Service Model] (SM). The SM is an abstract specification of services any
openEHR implementation can provide. Currently the only concrete
imlementable spec for SM is the
https://specifications.openehr.org/releases/ITS-REST/latest[openEHR REST
API], that is why the openEHR REST API is considered an ITS artifact
(Implementable Technology Specification).

== General considerations

=== Preconditions

[arabic]
. It should be able to run test suites against a clean server:
* There are no EHRs
* There are no commits (COMPOSITIONs, VERSIONs)
* There are no templates or archetypes loaded
. The server under test should provide some kind of authorization
mechanism, for instance an auth endpoint on the REST API, or provide
some kind of token, etc.

=== Considerations

[arabic]
. The server under test should be classified as "`Custom API`" or
"`openEHR API`" (compliant with the openEHR REST API). This is needed in
order to implement tests in code.
. The supported IM version(s) by the server under test should be stated
beforehand, because this will determine some variations on the data sets
used for testing. The minimum required version is 1.0.2.
. In most test frameworks pre conditions, setup, actions, post
conditions, and cleansteps can be implemented
* PRE would be to ensure the server is on a known state,
* SETUP is for creating a specific state knowing the PRE is satisfied
(for instance this will load some data),
* then ACTIONS will alter that state and should not fail (actions can be
positive or negative),
* POST is a set of assertions that should be satisfied by the state
after the ACTIONS, and
* CLEAN is leaving the server in the state found at PRE.

== Test Suites

The following diagram shows the different components, suites, and test
cases inlcuded in this Conformance Testing Specification.

[.image]#Test Suites#

=== Test Suite Components

==== Knowledge

This component includes the test suites for Operational Templates (OPT),
Archetype Definition Language (ADL) and Terminology.

Since our focus was on OPT-based systems, the ADL component wasn’t
developed here.

The current status of an openEHR Terminology component is not completely
defined by the current specifications, that component wasn’t developed.

We’ll leave both ADL and TERM test suites as placeholders here.

link:KNOWLEDGE.md[Knowledge Test Suite]

==== EHR

This component includes the test suites for EHR and EHR_STATUS, which
test services related to EHR management.

link:EHR.md[EHR Test Suite]

==== EHR/COMPOSITION

This component includes the test suite for COMPOSITION related services,
containing test cases focused on information content, including
creation, modification and versioning.

link:EHR_COMPOSITION.md[EHR/COMPOSITION Test Suite]

==== EHR/CONTRIBUTION

This component includes the test suite for CONTRIBUTION related
services, containing test cases focused on EHR data management,
including creation, modification and versioning of COMPOSITION,
EHR_STATUS and FOLDER.

link:EHR_CONTRIBUTION.md[EHR/CONTRIBUTION Test Suite]

==== DIRECTORY

This component includes the test suite for EHR.directory related
services, which help to organize clinical documents inside the EHR.

link:DIRECTORY.md[DIRECTORY]

=== Test Case Dependencies

The following diagram shows the dependencies between the test cases.
This is important since it shows in which order the different services
should be used. For instance, the data required to execute one service
should be created first by using another service.

The arrows should be interpreted as "`depends on`".

[.image]#Test Suites#
