= Functional Conformance: Messaging Component

// Some useful links: 
:i_message_service_link: {openehr_sm_openehr_platform}#_i_message_service_interface
:i_ehr_extract_link: {openehr_sm_openehr_platform}#_i_ehr_extract_interface
:i_tdd_link: {openehr_sm_openehr_platform}#_i_tdd_interface

== Normative Reference

Items in this validation suite conceptually use the following abstract interfaces from the {i_message_service_link}[Abstract Platform Service Model, MESSAGE component^].

* `I_EHR_EXTRACT`
* `I_TDD`

These are concretely realised in implementation technology specfic APIs, such as the {openehr_message_rest_api}[MESSAGE REST API^].

The data that flow through these interfaces are defined by the following information model specifications:

* Service Interfaces:
** {openehr_sm_openehr_platform}#_message_package[Abstract Message Service Model^]
* Information Models:
** {openehr_rm_ehr_extract}[EHR Extract IM^]
** {openehr_rm_ehr}[EHR IM^]
** {openehr_rm_demographic}[Demographic IM^]
** {openehr_rm_common}[Common IM^]
** {openehr_rm_data_structures}[Data Structures IM^]
** {openehr_rm_data_types}[Data Types IM^]
** {openehr_rm_support}[Support IM^]

== Dependencies

TBD

== Test Environment

[width="5%",cols="100%",]
|===
|TBD
|===

== Test Data Sets

[width="5%",cols="100%",]
|===
|TBD
|===

== Test Cases

=== Conformance point: I_EHR_EXTRACT.export_ehr()

Platform service ref: {i_ehr_extract_link}[`I_EHR_EXTRACT._export_ehr()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_EHR_EXTRACT.export_ehr_extract()

Platform service ref: {i_ehr_extract_link}[`I_EHR_EXTRACT._export_ehr_extract()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_EHR_EXTRACT.export_ehr()

Platform service ref: {i_ehr_extract_link}[`I_EHR_EXTRACT._export_ehr()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_EHR_EXTRACT.export_ehrs()

Platform service ref: {i_ehr_extract_link}[`I_EHR_EXTRACT._export_ehrs()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_EHR_EXTRACT.export_ehr_extracts()

Platform service ref: {i_ehr_extract_link}[`I_EHR_EXTRACT._export_ehr_extracts()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_TDD.import_tdd()

Platform service ref: {i_tdd_link}[`I_TDD._import_tdd()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_TDD.import_tdds()

Platform service ref: {i_tdd_link}[`I_TDD._import_tdds()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD
