= Functional Conformance: Demographic Component

// Some useful links: 
:i_demographic_service_link: {openehr_sm_openehr_platform}#_i_demographic_service_interface
:i_party_link: {openehr_sm_openehr_platform}#_i_party_interface
:i_party_relationship_link: {openehr_sm_openehr_platform}#_i_party_relationship_interface

== Normative Reference

Items in this validation suite conceptually use the following abstract interfaces from the {i_demographic_service_link}[Abstract Platform Service Model, DEMOGRAPHIC component^].

* `I_DEMOGRAPHIC_SERVICE`

These are concretely realised in implementation technology specfic APIs, such as the {openehr_ehr_rest_api}[EHR REST API^].

The data that flow through these interfaces are defined by the following information model specifications:

* Service Interfaces:
** {openehr_sm_openehr_platform}#_demographic_package[Abstract Demographic Service Model^]
* Information Models:
** {openehr_rm_demographic}[Demographic IM^]
** {openehr_rm_common}[Common IM^]
** {openehr_rm_data_structures}[Data Structures IM^]
** {openehr_rm_data_types}[Data Types IM^]
** {openehr_rm_support}[Support IM^]
** {openehr_rm_common}#_change_control_package[Versioning^]

== Dependencies

This test suite depends on other test suites:

* <<_func_conf_def_component, Functional Conformance: Definitions Component>>, providing OPTs.

== Test Environment

[width="5%",cols="100%",]
|===
|TBD
|===

== Test Data Sets

[width="5%",cols="100%",]
|===
|TBD
|===

== Test Cases

=== Conformance point: I_DEMOGRAPHIC_SERVICE.create_party()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._create_party()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD

=== Conformance point: I_DEMOGRAPHIC_SERVICE.get_party()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._get_party()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.get_party_at_time()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._get_party_at_time()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.update_party()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._update_party()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.delete_party()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._delete_party()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.get_party_at_version()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._get_party_at_version()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.create_party_relationship()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._create_party_relationship()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD

=== Conformance point: I_DEMOGRAPHIC_SERVICE.get_party_relationship()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._get_party_relationship()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.get_party_relationship_at_time()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._get_party_relationship_at_time()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.update_party_relationship()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._update_party_relationship()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.delete_party_relationship()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._delete_party_relationship()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_DEMOGRAPHIC_SERVICE.get_party_relationship_at_version()

Platform service ref: {i_demographic_service_link}[`I_DEMOGRAPHIC_SERVICE._get_party_relationship_at_version()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD

                                                                            
