= Overview

== Scope

As described in the {openehr_cnf_guide}#_product_scope[openEHR Conformance Guide^], the following aspects of a System Under Test (SUT) are tested to determine conformance to published specifications:

[cols="1,2,2", options="header"]
|===

|Test aspect
|How assessed
|Methodology

|*API conformance*
|Conformance of the _implemented APIs_ to the published APIs, in a concrete API technology
|Regression of test client running API call-in test cases against reference results

|*Data Validation conformance*
|Conformance of platform's _validation of data against semantic models_ (archetypes etc)
|Regression of test client committing variable data sets against reference validity

|===

The main part of this specification is divided into sections according to the three test aspects shown above. Specific methods related to each aspect are described in the sub-sections below.

Specific applications are also outside the scope of this specification, however, it is assumed that in order for solutions to be testable, a minimal generic viewing tool is provided to enable viewing of data and other testable events.

== API Conformance Test Design

API conformance is assessed by running tests on the SUT API, and determining deviations from expected results. As described in link:{openehr_cnf_guide}#_from_specifications_to_runnable_tests[Section 4.2 of the openEHR Conformance Guide^], the test cases defined here are based on the {openehr_sm_openehr_platform}[openEHR Platform Abstract Service Model^] API operations. Each such operation is a __testable capability of a system that relates to a business function__. For example, SM operations for an EHR service include `create_EHR`, `update_EHR`, and so on. For any such operation, there may be multiple test cases, each of which is individually identified. For each test case, there may be multiple data sets. A 'test' is therefore the execution of a particular test case with a particular data set.

Each test case is documented in the form shown in the following sub-section.

=== Test Case <SERVICE_COMPONENT>.<operation>-<test-specific id>

[cols="1h,4a"]
|===
|Description    | <test case description>
|Pre-conditions | <conditions required of the SUT prior to test case execution>
|Post-conditions| <conditions true of the SUT subsequent to test case execution>
|Flow           | <steps required to execute the test>
|===

In most automated test frameworks, pre-conditions, setup, actions, post-conditions, and cleanup steps can be directly implemented.

NOTE: The supported RM version(s) by the SUT should be stated in the Conformance Statement, because this will determine some variations on the data sets used for testing. The minimum required version is RM 1.0.2.

== Data Validation Conformance Test Design

Data validation conformance is defined in terms of test cases with multiple data sets. These test cases are documented in the same basic way as described above, along with multiple data sets, typically shown in tabulated form. They are described in <<_data_validation_conformance>>.

