= Overview

== Scope

As described in the {openehr_cnf_guide}#_product_scope[openEHR Conformance Guide^], the following aspects of a System Under Test (SUT) are tested to determine conformance to published specifications:

[cols="1,2,2", options="header"]
|===

|Test aspect
|How assessed
|Methodology

|*Functional conformance*
|Conformance of the _implemented APIs_ to the published APIs, in a concrete API technology
|Regression of test client running API call-in test cases against reference results

|*Semantic conformance*
|Conformance of platform's _content validation_ of data against semantic models (archetypes etc)
|Regression of test client committing variable data sets against reference validity

|*Critical attributes*
|Conformance of specific platform _non-functional_ properties to specification
|Various

|===

The main part of this specification is divided into sections according to the three test aspects shown above. Specific methods related to each aspect are described in the sub-sections below.

This specification does not cover claims to non-functional characteristics such as capacity, performance, availability, or consistency of systems. It is however recommended that supply agreements for operational solutions include criteria for these factors, as relevant to the situation. 

It may be possible to develop a band-based rating sytem for capacity. Performance, availability, consistency and related characteristics may be assessed using a framework that takes account of the CAP and / or PACELC theorems.

Specific applications are also outside the scope of this specification, however, it is assumed that in order for solutions to be testable, a minimal generic viewing tool is provided to enable viewing of data and other testable events.

== Functional conformance

Functional conformance is assessed by running tests on the SUT API, and determining deviations from known reference responses. As described in  link:{openehr_cnf_guide}#_from_specifications_to_runnable_tests[Section 4.2 of the openEHR Conformance Guide^], the test cases defined here are based on the {openehr_sm_openehr_platform}[openEHR Platform Abstract Service Model^] API calls, which are termed 'conformance points'. A conformance point is understood as a __testable capability of a system that relates to a business function__. For example, conformance points for an EHR service include `create_EHR`, `update_EHR`, and so on. For any given conformance point, there may be multiple tests, each of which is individually identified.

Each test case is documented in the following form.

=== TC <Identifier, e.g. TC EHR_COMPOSITION.has_composition_bad_composition>

[cols="1h,4a"]
|===
|Description    | <test case description>
|Pre-conditions | <conditions required of the SUT prior to test case execution>
|Post-conditions| <conditions true of the SUT subsequent to test case execution>
|Flow           | <steps required to execute the test>
|===

In most automated test frameworks, pre-conditions, setup, actions, post-conditions, and cleanup steps can be directly implemented.

NOTE: The supported RM version(s) by the server under test should be stated beforehand, because this will determine some variations on the data sets used for testing. The minimum required version is 1.0.2.

== Semantic conformance

TBD

== Critical attributes

TBD

