= Functional Conformance: Querying Component

// Some useful links: 
:i_query_service_link: {openehr_sm_openehr_platform}#_i_query_service_interface

== Normative Reference

Items in this validation suite conceptually use the following abstract interfaces from the {i_query_service_link}[Abstract Platform Service Model, QUERY component^].

* `I_QUERY_SERVICE`

These are concretely realised in implementation technology specfic APIs, such as the {openehr_query_rest_api}[QUERY REST API^].

The data that flow through these interfaces are defined by the following information model specifications:

* Service Interfaces:
** {openehr_sm_openehr_platform}#_query_package[Abstract Query Service Model^]
** {openehr_query_rest_api}[Query REST API^]
* Language Specifications:
** {openehr_query_aql}[AQL specification^]

== Dependencies

This test suite depends on other test suites:

* <<_func_conf_def_component, Functional Conformance: Definitions Component>>, providing OPTs.

== Test Environment

[width="5%",cols="100%",]
|===
|TBD
|===

== Test Data Sets

[width="5%",cols="100%",]
|===
|TBD
|===

== Test Cases

=== Conformance point: I_QUERY_SERVICE.execute_stored_query()

Platform service ref: {i_demographic_service_link}[`I_QUERY_SERVICE._execute_stored_query()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD


=== Conformance point: I_QUERY_SERVICE.execute_ad_hoc_query()

Platform service ref: {i_demographic_service_link}[`I_QUERY_SERVICE._execute_ad_hoc_query()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD

=== Conformance point: I_QUERY_SERVICE.execute_stored_query()

Platform service ref: {i_demographic_service_link}[`I_QUERY_SERVICE._execute_stored_query()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD

=== Conformance point: I_QUERY_SERVICE.execute_stored_query()

Platform service ref: {i_demographic_service_link}[`I_QUERY_SERVICE._execute_stored_query()_`^]

==== TC aaaa

TBD

==== TC bbbb

TBD

