= Overview

Conformance testing is used as the basis of product certification, and has the following goals:

* _Tendering_: enable tendering authorities to state formal criteria for compliance in tenders
* _Protection for solution developers_: enables bona fide vendors and other developers to prove the quality of their solutions compared to other offerings claiming conformance
* _Protection for procurement_: provides a way of ensuring that purchased solutions can be contractually guaranteed to perform in certain ways

== Scope

This specification describes the _conformance points_ for _openEHR platform products_ whose semantics are based on openEHR Foundation specifications. Such systems typically include data services (i.e. persistence & querying) along with various options dependent on the orientation of the product and its maturity; these may include integration capabilities, domain services (e.g. guidelines, planning) and so on. It does not cover applications or modelling tools.

A conformance point is understood as a _testable capability of a system that relates to a business function_. For example, conformance points for an EHR persistence service (aka Clinical Data Repository, or CDR) may include 'create EHR', 'update EHR', 'versioning' etc. Conformance points are based on {openehr_sm_openehr_platform}[openEHR Platform Abstract Service Model^] API calls.

One or more methods of testing each conformance point is described in this specification. Conformance testing is based on comparing system behaviour to the relevant openEHR published specifications.

Fine-grained system capabilities naturally aggregate in various ways to produce specific coarse-grained business-relevant profiles, such as for a 'minimally viable openEHR system' and so on. In order to provide the customer side with a means of determining what constitute sensible sets of requirements, the specification defines a set of _profiles_.

The scope of this specification is limited to the following:

* (specific) functional capabilities of systems;
* limited non-functional capabilities, including:
** external data format used by exposed APIs;
** security and privacy.

The system under test is accessed via one or more concrete protocol APIs, each of which is defined in the relevant openEHR Specification.

This specification does not cover claims to other non-functional characteristics such as capacity, performance, availability, or consistency of systems. It is however recommended that supply agreements for operational solutions include criteria for these factors, as relevant to the situation. 

It may be possible to develop a band-based rating sytem for capacity. Performance, availability, consistency and related characteristics may be assessed using a framework that takes account of the CAP and / or PACELC theorems.

Specific applications are also outside the scope of this specification, however, it is assumed that in order for solutions to be testable, a minimal generic viewing tool is provided to enable viewing or data and other testable events.
