= Preface

== Purpose

This document describes the openEHR EHR System Conformance Definition, which states a test schedule and content of tests to be used to determine the conformance of EHR solutions to openEHR EHR specifications. The audience of this document includes:

* Software development organisations developing EHR systems;
* Customer organisations.

== Related Documents

Useful references for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_cnf_openehr_platform}[{openehr_domain}/releases/CNF/latest/openehr_platform_conformance.html].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content. Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira_prs_cnf}[specifications issue tracker].


