= Profiles

The schedule above describes capabilities of openEHR platform products that can be tested against the published specifiations via the REST APIs. These capabilities are grouped into _profiles_ to provide a guide to what constitutes the required functionality for particular category of solution.

A profile may be defined logically as a particular list of capabilities from the above schedule that may be combined to specify a particular kind of solution. For example, an openEHR Demographics product would treat most or all of the Demographic capabilities as mandatory, along with support for definitions, logging etc.

This specification defines a set of 'default profiles' intended as a guide for determining the minimum capabilities to specify in order to obtain certain basic levels of functionality.

== Default Profiles

The profiles used below are as follows:

* *CORE*: a minimal functional openEHR platform implementation that enables the storage and retrieval of openEHR EHR data;
* *STANDARD*: a 'standard' configuration of capabilities that adds AQL querying and logging to the CORE;
* *OPTIONS*: components that are considered optional for non-specialised solutions.

In order to obtain `CORE` or `STANDARD` conformance, all mentioned capabilities must be met in testing. The `OPTIONS` profile is a catch-all pseudo-profile that covers all testable capabilities not included in `CORE` or `STANDARD`; `OPTIONS` is obtained if any optional capability is passed in testing.

=== Functional

[cols="1,1,^1,^1,^1", options="header"]
|===
|Product Component
                |Capability             |CORE       |STANDARD       |OPTIONS

.5+|*EHR +
 Persistence*   |OPT 1.4                |&#10004;   |&#10004;       |
                |EHR data              ^|&#10004;   |&#10004;       |          
                |Versioning            ^|&#10004;   |&#10004;       |          
                |Archetype +
                 validation            ^|&#10004;   |&#10004;       |          
                |Logging               ^|           |&#10004;       |

.4+|*Demographic +
 Persistence*   |Demographic data       |           |               |?
                |Versioning            ^|           |               |?
                |Archetype +
                 validation            ^|           |               |?
                |Logging               ^|           |               |?

.2+|*Messaging*
                |EHR Extract            |           |               |?
                |TDS                   ^|           |               |?

.4+|*Querying*  |Stored queries         |           |&#10004;       |
                |AQL basic			   ^|           |&#10004;		|
                |AQL advanced          ^|           |               |?
                |AQL + terminology     ^|           |               |?

.7+|*Admin*     |List transactions      |           |               |?
                |Transaction +
                 statistics            ^|           |               |?
                |Bulk EHR export       ^|           |               |?
                |Bulk EHR load         ^|           |               |?
                |Archive EHRs          ^|           |               |?
                |Delete EHRs           ^|           |               |?
                |Delete Demographics   ^|           |               |?

.7+|*APIs*      |DEFINITIONS REST API   |&#10004;   |&#10004;       |
                |EHR REST API          ^|&#10004;   |&#10004;       |
                |DEMOGRAPHIC REST API  ^|			|				|?
                |QUERY REST API        ^|           |&#10004;       |
                |CDS REST API          ^|           |               |?
                |ADMIN REST API        ^|           |               |?
                |TDD REST API          ^|           |               |?

.2+|*Application +
 services*      |GDL                    |           |               |?
                |Task Planning         ^|           |               |?
                
|===

=== Non-Functional

[cols="1,1,^1,^1,^1", options="header"]
|===
|Product Attribute
                |Capability         |CORE       |STANDARD       |OPTIONS

.3+|*Security & +
 Privacy*       |Signing            |           |&#10004;       |
                |Anonymous EHRs    ^|&#10004;   |&#10004;       |
                |Info Consent      ^|           |               |?
                
|===

=== Other Non-Functional

[cols="1,1", options="header"]
|===
|Product Attribute                  |Values

|*External Data Format*             |XML, JSON
                
|===

