= Conformance Schedule

== Overview

The following table shows the schedule according to which functional conformance claims can be made for a _product component_, corresponding to a block of the same name on the above diagram. Each product component has one table.

=== Understanding the conformance tables

[cols="1,1,3,2,2", options="header"]
|===
|Capability             |Conformance Point          |Description                        |Test script            |REST script
                
|Claimed capability +
 of the component       |Testable characteristic +
                         within this capability     |description of conformance point.  |Logical structure of + 
                                                                                         Test Case              |REST API test script +
                                                                                                                 (postman)
|===


== Conformance Test Tables

=== Archetype / Template Definitions

Specifications:
    
* {openehr_am_adl14}[ADL 1.4]
* {openehr_am_aom14}[AOM 1.4]
* {openehr_am_adl2}[ADL 2]
* {openehr_am_aom2}[AOM 2]
* {openehr_am_id}[Archetype Identification]


[cols="1,1,3,2", options="header"]
|===
|Capability             |Conformance Point          |Description                                        |Test script

.3+|*ADL 1.4 Archetype +
    provisioning*       |Upload archetype           |Upload an archetype to the server               .3+|DEF:upload archetype * N; +
                                                                                                         DEF:list archetypes
                        |Get archetype              |Get archetype by archetype_id                       DEF:get archetype by id

                        |List archetypes            |List all available archetypes on the system

.3+|*OPT 1.4 Operational +
    Template +
    provisioning*       |Upload template            |Upload a template to the server                 .3+|DEF:upload template * N; +
                                                                                                         DEF:list templates
                        |Get template               |Get template by template_id                         DEF:get template by id

                        |List templates             |List all available templates on the system

|===

=== EHR Persistence Component

Specifications:
    
* {openehr_rm_ehr}[EHR IM]
* {openehr_rm_common}[Common IM]
* {openehr_rm_data_structures}[Data Structures IM]
* {openehr_rm_data_types}[Data Types IM]
* {openehr_rm_support}[Support IM]
* {openehr_rm_common}#_change_control_package[Versioning]

[cols="1,2,3,2,1", options="header"]
|===
|Capability             |Conformance Point          |Description          |Test script      |REST script

.6+|*EHR Repository*         

    |Create EHR
    |Create a new EHR; EHR id generated by system
    |link:{scripts_dir}/create_ehr.txt[create_ehr, window="_blank"]
    |link:{scripts_dir}/postman/create_ehr.json[postman script]

    |Create EHR with EHR id
    |Create new EHR with the specified EHR id
    |link:{scripts_dir}/create_ehr_with_id.txt[create_ehr_with_id, window="_blank"]
    |link:{scripts_dir}/postman/create_ehr_with_id.json[postman script]

    |Create EHR for subject
    |Create new EHR with the specified subject id; EHR id generated by system
    |link:{scripts_dir}/create_ehr_for_subject.txt[create_ehr_for_subject, window="_blank"]
    |link:{scripts_dir}/postman/create_ehr_for_subject.json[postman script]

    |Create EHR with EHR id and subject id
    |Create new EHR with the specified EHR id and subject id.
    |link:{scripts_dir}/create_ehr_with_id_and_subject.txt[create_ehr_with_id_and_subject, window="_blank"]
    |link:{scripts_dir}/postman/create_ehr_for_subject.json[postman script]

    |Get EHR
    |Get EHR with the specified EHR identifier.
    |
    |

    |Get EHRs for subject
    |Get EHR(s) for specified subject.
    |link:{scripts_dir}/get_ehrs_for_subject.txt[get_ehrs_for_subject, window="_blank"]
    |

.5+|*EHR Retrieve and Modify*         

    |Get EHR active status
    |Get `EHR_STATUS._is_modifiable_`
    |
    |

    |Get EHR queryable status
    |Get `EHR_STATUS._is_queryable_`
    |
    |
    
    |Set EHR inactive
    |Update `EHR_STATUS._is_modifiable_` to False
    |
    |

    |Set EHR non-queryable
    |Update `EHR_STATUS._is_queryable_` to False
    |
    |

    |Set EHR status details
    |Update `EHR_STATUS._other_details_`
    |
    |

.5+|*Composition Retrieve and Modify*  

    |Create Composition
    |Create new `COMPOSITION` with implicit Contribution
    |link:{scripts_dir}/create_composition.txt[create_composition, window="_blank"]
    |

    |Get Composition by id
    |Get `COMPOSITION` by id
    |
    |

    |Get Composition at time
    |Get `COMPOSITION` at time
    |
    |

    |Update Composition
    |Create a new version of a `COMPOSITION`
    |
    |

    |Delete Composition
    |Logically delete a `COMPOSITION`
    |
    |
                   
.2+|*Directory Retrieve and Modify*

    |Create directory
    |
    |
    |

    |Update directory
    |
    |
    |

.5+|*Change sets*

    |Commit simple change set
    |Commit `CONTRIBUTION` with `COMPOSITION` 
    |
    |

    |Commit mixed content change set
    |Commit `CONTRIBUTION` with multiple `COMPOSITIONs` , `DIRECTORY`
    |
    |

    |Commit mixed update change set
    |Commit `CONTRIBUTION` with `COMPOSITION` add, updated, deleted
    |
    |

    |Get change set
    |Get `CONTRIBUTION` by id
    |
    |

    |List Change Sets
    |List Contributions
    |
    |

.9+|*Versioning*

    |Get Versioned Ehr status
    |
    |
    |

    |Get Ehr_status version by id
    |                                                   
    |
    |

    |Get Ehr_status version at time
    |
    |
    |

    |Get Versioned Directory
    |
    |
    |

    |Get Directory version by id
    |                                                   
    |
    |

    |Get Directory version at time
    |
    |
    |

    |Get Versioned Composition
    |
    |
    |

    |Get Composition version by id
    |
    |
    |

    |Get Composition version at time
    |
    |
    |

 .3+|*Archetype +
     validation*        
     
    |Accept valid content
    |xxx
    |
    |

    |Reject invalid archetype
    |xxx
    |
    |

    |Reject invalid content
    |xxx
    |
    |

 .3+|*Logging*
 
    |Log creates
    |xxx
    |
    |

    |Log updates
    |xxx
    |
    |

    |Log reads
    |xxx
    |
    |

|===

=== Demographic Persistence Component

Specifications:

* {openehr_rm_demographic}[Demographic IM]
* {openehr_rm_common}[Common IM]
* {openehr_rm_data_structures}[Data Structures IM]
* {openehr_rm_data_types}[Data Types IM]
* {openehr_rm_support}[Support IM]
* {openehr_rm_common}#_change_control_package[Versioning])

[cols="3,3,3", options="header"]
|===

|Capability             |Conformance Point          |Test script

.3+|*Demographic data*
                        |Create Party           |DEM:create party; +
                                                 DEM:retrieve party; +
                                                 regression diff

                        |Update PARTY           |DEM:create party; +
                                                 DEM:retrieve party; +
                                                 DEM:update party; +
                                                 DEM:retrieve party; +
                                                 regression diff

                        |Retrieve PARTY         |xxx

    |*Versioning*       |Commit Party group +
                         change set             |xxx

 .3+|*Archetype +
     validation*        |Accept valid content   |DEM:create_xxx; +
                                                 check sys log
                        |Reject invalid +
                        archetype               |DEM:create_xxx; +
                                                 check sys log

                        |Reject invalid content |DEM:create_xxx; +
                                                 check sys log
 .3+|*Logging*         |Log creates            |DEM:create_xxx; +
                                                 check sys log
                                                
                        |Log updates            |DEM:commit_xxx; +
                                                 check sys log
                                                
                        |Log reads              |DEM:retrieve_xxx; +
                                                 check sys log

|===

[.tbd]
TODO: In theory we could include Integration Entries ({openehr_rm_integration}[Integration IM]), but I don't think anyone uses them. I suspect that spec should be retired.

=== Messaging Component

Specifications:

* {openehr_rm_ehr_extract}[EHR Extract IM]
* {openehr_rm_ehr}[EHR IM]
* {openehr_rm_demographic}[Demographic IM]
* {openehr_rm_common}[Common IM]
* {openehr_rm_data_structures}[Data Structures IM]
* {openehr_rm_data_types}[Data Types IM]
* {openehr_rm_support}[Support IM]


[cols="3,3,3", options="header"]
|===
|Capability             |Conformance Point      |Test script

.5+|*EHR Extract*
                        |Export openEHR Extract +
                         1 patient              |EHRX:

                        |Export openEHR Extract +
                         w/ versions            |EHRX:

                        |Export openEHR Extract +
                         multiple patients      |EHRX:

                        |Export generic Extract +
                         1 patient              |EHRX:

                        |Export whole +
                         patient record         |EHRX:

|*Template Data +
 Schema (TDS)*          |TDD commit             |TDD:
                 
|===


=== Querying Product Component

Specifications:

* {openehr_query_aql}[AQL specification]

[cols="3,3,3,3", options="header"]
|===
|Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.2+|*Stored queries*   |Store query            |DEFINITIONS API        |DEF:create stored query; +
                                                                     DEF:get stored query; +
                                                                     DEF:list stored queries

                    |Delete query           |DEFINITIONS API        |DEF:create stored query; +
                                                                     DEF:delete stored query; +
                                                                     DEF:get stored query; +
                                                                     DEF:list stored queries

|*AQL basic*        |Patient-centric        |QUERY API              |EHR:commit composition x N; +
                                                                     QRY:execute ad hoc query +
                                                                     regression.

.2+|*AQL advanced*     |Patient-centric        |QUERY API              |EHR:commit composition x N; +
                                                                     AQL:create stored query; +
                                                                     QRY:execute stored query; +
                                                                     QRY:execute ad hoc query; +
                                                                     regression.

                    |Population query       |QUERY API              |EHR:commit composition x N; +
                                                                     AQL:create stored query; +
                                                                     QRY:execute stored query; +
                                                                     QRY:execute ad hoc query; +
                                                                     regression.
.2+|*AQL + + 
 terminology*       |Patient-centric        |QUERY API              |EHR:commit composition x N; +
                                                                     AQL:create stored query; +
                                                                     QRY:execute stored query; +
                                                                     QRY:execute ad hoc query; +
                                                                     regression.

                    |Population query       |QUERY API              |EHR:commit composition x N; +
                                                                     AQL:create stored query; +
                                                                     QRY:execute stored query; +
                                                                     QRY:execute ad hoc query; +
                                                                     regression.

|===


=== Admin Product Component

Specifications:

* xxx

[cols="3,3,3,3", options="header"]
|===
|Capability             |Conformance Point      |Access method             |Test script

|*List transactions*    |List CONTRIBUTIONs +
                         since time             |ADMIN API              |ADM:
.2+|*Transaction +
statistics*        |Get CONTRIBUTION +
                 count since time       |ADMIN API              |ADM:

                |Get COMPOSITIONs +
                 add/mod/del +
                 since time             |ADMIN API              |ADM:

|*Bulk EHR Export*  |Export all EHRs        |ADMIN API              |EHR:create EHR x N; + ;
                                                                 EHR:commit composition x N; + 
                                                                 ADM:export; +
                                                                 file test / diff

|*Bulk EHR Load*    |Load complete file     |ADMIN API              |ADM:load; +
                                                                 ADM:retrieve x N
|*Archive EHRs*     |Archive EHRs by +
                 identifier             |ADMIN API              |ADM:archive; +
                                                                 review archive;
                                                                 confirm status on +
                                                                 archived EHRs
|*Physical EHR +
delete*     		|Delete EHR by +
                 identifier             |ADMIN API              |ADM:delete_ehr
|*Physical +
Demographics +
delete*     		|Delete PARTY by +
                 identifier             |ADMIN API              |ADM:delete_party
|===

=== API Product Component

Specifications:

* xxx

[cols="3,3,3,3", options="header"]
|===
|Product +
 Component
                |Capability        |Conformance +
                                    point                   |Access Method          |Test Script
                
.7+|*REST APIs* |*DEFINITIONS API* |???                     |DEFINITIONS API        |Exercise all functions +
                                                                                     & arguments

                |*EHR API*         |???                     |EHR API                |Exercise all functions +
                                                                                     & arguments
                                                                                     
                |*DEMOGRAPHIC API* |???                     |DEMOGRAPHIC API        |Exercise all functions +
                                                                                     & arguments
                                                                                     
                |*QUERY API*       |???                     |QUERY API              |Exercise all functions +
                                                                                     & arguments
                                                                                         
                |*CDS API*         |???                     |CDS API                |Exercise functions +
                                                                                     & arguments
                                                                                         
                |*ADMIN API*       |???                     |ADMIN API              |Exercise functions +
                                                                                     & arguments
                                                                                         
                |*TDD API*         |???                     |TDD API                |Exercise functions +
                                                                                     & arguments
|===

=== Non-Functional Characteristics

Specifications:

* {openehr_rm_common}#_digital_signature[Digital Signature]
* {openehr_overview}#_overview_4[EHR/Demographic separation]


[cols="2,3,3,3,3", options="header"]
|===
|Product Attribute
                |Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.3+|*Security & +
 Privacy*
                |*Signing*          |???                    |xxx API                |Commit/Retrieve +
                                                                                     data regression
                |*Anonymous EHRs*   |???                    |EHR API                |Commit/query
                |*Info Consent*     |???                    |xxx API                |Commit/Retrieve +
                                                                                     data regression
|===

=== Tools

Tools supplied with an openEHR EHR solution should include:

* generic EHR viewer - a generic web portal for viewing EHR data in generic form.

