= Conformance Schedule

== Overview

This section contains the schedule according to which conformance claims can be made for a a product. The conformance test schedule is divided into functional and non-functional parts, for which the structures are slightly different. 

Functional conformance is on the basis of _product component_, i.e. 'EHR persistence', 'Querying' etc, each corresponding to a named block on the above SUT diagram. Each product component has one table in this schedule. Formal conformance points, defined in terms of calls in the relevant component service interface, are listed in the second column of the table. The first column groups conformance points under 'capability', which is understood as a marketing term reflecting coarse-grained functionality, and is _used as the basis for conformance profiles_ described in the next section. 

The remaining columns but one describe each 'semantic' conformance point, and define the logic of a conformance test case for it, expressed as Java-like pseudo-code. In many cases, one test script may be used to test multiple conformance points. 

The final column(s) provides the implementation of the test case for REST web services over HTTP. Each other protocol will result in a new column on the right.

The following illustrates the conformance table structure for functional components.

[cols="2,2,3,2,2", options="header"]
|===
|Capability             |Conformance Point +
                         (Service Model call)   |Description                            |Test case script      |REST script
                
|Claimed capability +
 of the component.      |Testable characteristic +
                         defined in terms of +
                         abstract service model call.|Description of conformance point.  |Logical test case + 
                                                                                         script (pseudo-code)   |REST API test script +
                                                                                                                 (postman)
|===

For the small number of system non-functional characteristics for which conformance is defined here, the table structure is the same. However, conformance points are not formally defined by the openEHR Service Model, but informally defined by this specification.

