= Conformance Certificate

An openEHR Conformance Certificate consists of a rating in the Functional and Content dimensions, and a detailed report. The ratings are as follows:

[cols="2,1,4", options="header"]
|===
|Characteristics            |Levels			|Description

.3+|*Functional*            |CORE			|Core functionality required for operational deployment.
                            |STANDARD       |More comprehensive capabilities useful in a 'standard' EHR operational environment.
                            |OPTIONS     	|Optional features required in specific circumstances.

.2+|*Non-functional*        |BASIC-SEC      |Basic security features.
                            |BASIC-PRIV     |Basic privacy features.
                    
.2+|*External data format*  |Canonical XML  |openEHR Canonical XML, defined by published XSDs
                            |Canonical JSON |openEHR Canonical XML, defined by published transform of XML

|===

An awarded certificate for a typical system will look as follows:

------
openEHR Conformance Certificate
===============================

Solution:       BestEHR release 2.4
                details ...
Vendor:         ACME EHR systems LLC, Maxperformancia
Assessor:       openEHR Foundation
Infrastructure: openEHR CNF-test WS 1.5.0 on AWS ...
                System under test on AWS ...
Date:           12 April 2017
    
Certified conformance
=====================
Functional:     CORE, Extras
Sec & Priv:     xxx
Ext Data Fmt:   XML, JSON


Detailed Test Report
====================

+==============+=============+===============+=============================+==================+========+
|SUT           |openEHR      |Capability     |Conformance point            |Test              |Result  |
|Component     |Component    |(PROFILE)      |                             |Case              |        |
+==============+=============+===============+=============================+==================+========+
|ACME CDR      |EHR          |EHR Operations |I_EHR_SERVICE.               |                  |        |
|              |persistence  |               |create_ehr()                 |tc_ehr-create     |pass    |
|              |             +---------------+-----------------------------+------------------+--------+
|              |             |Versioning     |I_EHR_COMPOSITION.           |                  |        |
|              |             |               |get_versioned_composition()  |tc_ehr-vers       |pass    |
|              |             |               +-----------------------------+------------------+--------+
|              |             |               |I_EHR_CONTRIBUTION.          |tc_ehr-ctrb_smpl  |pass    |
|              |             |               |commit_contribution()        |tc_ehr-ctrb_cplx  |FAIL    |
+--------------+-------------+---------------+-----------------------------+------------------+--------+
|                                          . . . .                                                     |
+--------------+-------------+---------------+-----------------------------+------------------+--------+
|etc           |etc          |etc            |etc                          |etc               |        |
+==============+=============+===============+=============================+==================+========+


PROFILE REPORT
==============

+==============+================+====================================+===========+========+
|SUT           |openEHR         |Capability                          |Required   |Result  |
|Component     |Component       |                                    |in profile |
+==============+================+====================================+===========+========+
|ACME K-base   |Definitions     |ADL 1.4 archetype provisioning      |   Y       |pass    |
|              |                |ADL 1.4 OPT provisioning            |   Y       |pass    |
|              |                |Query provisioning                  |   Y       |pass    |
+--------------+----------------+------------------------------------+-----------+--------+
|ACME CDR      |EHR             |EHR Operations                      |   Y       |pass    |
|              |persistence     |EHR Status                          |   Y       |pass    |
|              |                |Composition Operations              |   Y       |pass    |
|              |                |Directory Operations                |   Y       |pass    |
|              |                |Change Sets                         |   Y       |pass    |
|              |                |Versioning                          |   Y       |pass    |
+--------------+----------------+------------------------------------+-----------+--------+
|ACME Konsole  |Admin           |Activity Report                     |   OPT     |FAIL    |
|              |                |Physical Delete                     |   N       |pass    |
|              |                |EHR Archive                         |   OPT     |pass    |
|                           .   .   .   .   .                                             |
|              |                |Signing                             |   OPT     |pass    |
+--------------+----------------+------------------------------------+-----------+--------+


------



