= Preface

== Purpose

This document describes the openEHR EHR System Conformance Definition, which states a test schedule and content of tests to be used to determine the conformance of EHR solutions to openEHR EHR specifications. The audience of this document includes:

* Software development organisations developing EHR systems;
* Customer organisations.

== Related Documents

Useful references for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_cnf_latest_guide}[{openehr_cnf_latest_guide}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_cnf_forum}[openEHR Conformance forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

