= Preface

== Purpose

This document describes the openEHR EHR System Conformance Definition, which states a test schedule and content of tests to be used to determine the conformance of EHR solutions to openEHR EHR specifications. The audience of this document includes:

* Software development organisations developing EHR systems;
* Customer organisations.

== Related Documents

Useful references for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at http://www.openehr.org/releases/CNF/latest/conformance_definition.html.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Tooling


