= Conformance Schedule

== Overview

The following table shows the schedule according to which functional conformance claims can be made for a solution.

=== Understanding the conformance tables

[cols="2,2,2,2,3", options="header"]
|===
|Product Component
                |Capability             |Conformance Point          |Access method             |Test script
                
|Component offered +
 in proposed system
                |Claimed capability +
                 of the component       |Testable characteristic +
                                         within this capability     |Method of communicating +
                                                                     with component             |Logical structure of +
                                                                                                 Test Case
|===


== Conformance Test Tables

=== Data Services

[cols="2,2,2,2,3", options="header"]
|===
|Product Component
                |Capability         |Conformance Point      |Access method             |Test script

.14+|*EHR +
    Persistence*
                |*OPT 1.4*          |Load OPT 1.4 files     |REST API or +
                                                             product-specific           |Load OPTs; list OPTs
             .6+|*EHR data*  +
                 +
                 (specs: +
                 {openehr_rm_ehr}[EHR IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                    |Create EHR             |EHR REST API               |API create call; +
                                                                                         API retrieve by Id call
                                    |EHR meta-data +
                                     & Status               |EHR REST API or +
                                                             generic viewer             |xxx
                                    |Update EHR +
                                     (CONTRIBUTIONs; +
                                      data based on +
                                      loaded OPTs)          |EHR REST API               |API commit call; +
                                                                                         API retrieve call; +
                                                                                         regression diff
                                    |Retrieve + 
                                     COMPOSITIONs           |EHR REST API               |API commit call; +
                                                                                         API retrieve call; +
                                                                                         regression diff
                                    |Create directory +
                                     (FOLDERs)              |EHR REST API               |API directory create call; +
                                                                                         API retrieve call; +
                                                                                         regression diff
                                    |Update directory +
                                     (FOLDERs)              |EHR REST API               |API directory update call; +
                                                                                         API retrieve call; +
                                                                                         regression diff

                |*Versioning* +
                 +
                 (specs: +
                 {openehr_rm_common}#_change_control_package[Versioning])
                                    |Contribution commit    |EHR REST API or +
                                                             generic viewer             |xxx

             .3+|*Archetype +
                 validation*         |Accept valid content   |EHR REST API               |xxx
                                    |Reject invalid archetype |EHR REST API             |xxx
                                    |Reject invalid content |EHR REST API               |xxx

             .3+|*Logging* +
                 +
                 (specs: +
                 openEHR IHE ATNA Profile)
                                    |Log creates            |EHR REST API, +
                                                             System Log                 |API create call; +
                                                                                         check sys log
                                    |Log updates            |EHR REST API, +
                                                             System Log                 |API commit call; +
                                                                                         check sys log
                                    |Log reads              |EHR REST API, +
                                                             System Log                 |API retriefve call; +
                                                                                         check sys log
                                            
.12+|*Demographic +
 Persistence*
                |*OPT 1.4*            |Load OPTs              |REST API or +
                                                             product-specific           |xxx
             .4+|*Demographic data*  +
                 +
                 (specs: +
                 {openehr_rm_demographic}[Demographic IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                    |Create Party           |Demographic REST API       |xxx
                                    |Update PARTY           |Demographic REST API       |xxx
                                    |Retrieve PARTY         |Demographic REST API       |xxx
                                    |Create/Retrieve +
                                     PARTY group            |Demographic REST API       |xxx

                |*Versioning* +
                 +
                 (specs: +
                 {openehr_rm_common}#_change_control_package[Versioning])
                                    |Contribution commit    |Demographic REST API or +
                                                             generic viewer             |xxx

             .3+|*Archetype +
                 validation*        |Accept valid content   |Demographic REST API       |API create call; +
                                                                                         check sys log
                                    |Reject invalid archetype |Demographic REST API     |API create call; +
                                                                                         check sys log
                                    |Reject invalid content |Demographic REST API       |API create call; +
                                                                                         check sys log
             .3+|*Logging*  +
                 +
                 (specs: +
                 openEHR IHE ATNA Profile)
                                    |Log creates            |Demographic REST API, +
                                                             System Log                 |API create call; +
                                                                                         check sys log
                                    |Log updates            |Demographic REST API, +
                                                             System Log                 |API commit call; +
                                                                                         check sys log
                                    |Log reads              |Demographic REST API, +
                                                             System Log                 |API retriefve call; +
                                                                                         check sys log

|===

[.tbd]
TODO: In theory we could include Integration Entries ({openehr_rm_integration}[Integration IM]), but I don't think anyone uses them. I suspect that spec should be retired.

=== Integration Capabilities

[cols="2,2,2,2,3", options="header"]
|===
|Product Component
                |Capability           |Conformance Point      |Access method             |Test script
                
.6+|*Messaging* 
             .5+|*EHR Extract* +
                 +
                 (specs: +
                 {openehr_rm_ehr_extract}[EHR Extract IM] +
                 {openehr_rm_ehr}[EHR IM] +
                 {openehr_rm_demographic}[Demographic IM] +
                 {openehr_rm_common}[Common IM] +
                 {openehr_rm_data_structures}[Data Structures IM] +
                 {openehr_rm_data_types}[Data Types IM] +
                 {openehr_rm_support}[Support IM])
                                        |Export openEHR Extract +
                                         1 patient              |Extract REST API           |???
                                        |Export openEHR Extract +
                                         w/ versions            |Extract REST API           |???
                                        |Export openEHR Extract +
                                         multiple patients      |Extract REST API           |???
                                        |Export generic Extract +
                                         1 patient              |Extract REST API           |???
                                        |Export whole +
                                         patient record         |Extract REST API           |???
                 
                |*Template Data +
                 Schema (TDS)*          |TDD commit             |TDD REST API               |???
                 

|===


=== Other Capabilities

[cols="2,2,2,2,3", options="header"]
|===
|Product Component
                |Capability         |Conformance +
                                     point                  |Access Method          |Test Script

.5+|*Querying* +
 +
 (specs: +
 {openehr_query_aql}[AQL specification])
                |*AQL basic*        |Basic patient-centric  |AQL REST API           |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
             .2+|*AQL advanced*     |Advanced patient- +
                                     centric                |AQL REST API           |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
                                    |Population query       |AQL REST API           |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
             .2+|*AQL + + 
                 terminology*       |Patient-centric        |AQL REST API           |Commit content; +
                                                                                     execute queries +
                                                                                     regression.
                                    |Population query       |AQL REST API           |Commit content; +
                                                                                     execute queries +
                                                                                     regression.

.2+|*Security & +
 Privacy* +
 +
 (specs: +
 {openehr_rm_common}#_digital_signature[Digital Signature] +
 {openehr_overview}#_overview_4[EHR/Demographic separation])
                |*Signing*          |???                    |EHR REST API           |Commit/Retrieve +
                                                                                     data regression
                |*Anonymous EHRs*   |???                    |EHR REST API           |Commit/query

.3+|*Data +
    Management* |*Bulk EHR Dump*    |Dump all EHRs          |EHR REST API           |API commit calls; + 
                                                                                     API dump call; +
                                                                                     file test / diff
                |*Bulk EHR Load*    |Load complete file     |EHR REST API, +
                                                             generic viewer         |API load call; +
                                                                                     API retrieve calls
                |*Archive EHRs*     |Archive EHRs by +
                                     identifier             |EHR REST API           |API archive call; +
                                                                                     review archive;
                                                                                     confirm status on +
                                                                                     archived EHRs
                
|===

=== APIs

[cols="2,2,2,2,3", options="header"]
|===
|Product Component
                |Capability         |Conformance +
                                     point                 |Access Method          |Test Script
                
.3+|*REST APIs* |*EHR REST API*     |???                    |EHR REST API           |Exercise all functions +
                                                                                     & arguments
                |*AQL REST API*     |???                    |AQL REST API           |Exercise functions +
                                                                                     & arguments
                |*TDD REST API*     |???                    |TDD REST API           |Exercise functions +
                                                                                     & arguments
|===

=== Tools

Tools supplied with an openEHR EHR solution should include:

* generic EHR viewer - a generic web portal for viewing EHR data in generic form.


== Profiles

The following table shows how the guideline conformance profiles may be defined with respect to the conformance criteria. These

[cols="1,1,^1,^1,^1", options="header"]
|===
|Product Component
                |Capability         |CORE       |STANDARD       |EXTRA

.5+|*EHR +
 Persistence*   |EHR data           |&#10004;   |&#10004;       |          
                |Versioning        ^|&#10004;   |&#10004;       |          
                |Archetype +
                 validation        ^|&#10004;   |&#10004;       |          
                |OPT 1.4           ^|&#10004;   |&#10004;       |
                |Logging           ^|           |&#10004;       |

.2+|*Integration*
                |EHR Extract        |           |               |+         
                |TDS               ^|           |               |+          

.3+|*Querying*  |AQL basic          |           |&#10004;       |
                |AQL advanced      ^|           |               |+
                |AQL + terminology ^|           |               |+

.2+|*Security & +
 Privacy*       |Signing            |           |               |+
                |Anonymous EHRs    ^|           |               |+
                
.3+|*APIs*      |EHR REST API       |&#10004;   |&#10004;       |
                |AQL REST API      ^|           |&#10004;       |
                |TDD REST API      ^|           |               |+

.5+|*Demographic +
 Persistence*   |Demographic data   |           |               |+         
                |Versioning        ^|           |               |+          
                |Archetype +
                 validation        ^|           |               |+         
                |OPT 1.4           ^|           |               |+
                |Logging           ^|           |               |+

.2+|*Application +
 services*      |GDL               ^|           |               |+
                |Task Planning     ^|           |               |+
|===

== SECTIONS BELOW TO BE REWRITTEN

== Core Semantics

RM Core consists of most of the RM, apart from the elements documented below under 'RM additional'.

[cols="1,3,3", options="header"]
|===
|Feature            |Specification                                                              |Tested by

|RM Core            |{openehr_rm_data_types}[Data Types IM] +
                     {openehr_rm_data_types}[Data Structures IM] +
                     {openehr_rm_common}[Common IM] +
                     {openehr_rm_ehr}[EHR IM]                                                   |
|OPT loading        |{openehr_oet_parser}/src/main/xsd[OET XSDs]                                |
|Versioning         |{openehr_rm_common}#_change_control_package[Common IM - +
                     Change Control Package] +
                     {openehr_overview}#_versioning_2[Architecture Overview]                    |
|Instruction State +
 Machine            |{openehr_rm_ehr}#_the_standard_instruction_state_machine_ism[EHR IM - ISM] |
|===

== Additional Semantics

[cols="1,3,3", options="header"]
|===
|Feature            |Specification                                                              |Tested by

|Folders            |{openehr_rm_common}#_directory_package[Common IM - Directory Package]      |
|RM Advanced DTs    |{openehr_rm_data_types}[Data Types IM - various]                           |
|RM Demograpics     |{openehr_rm_demographic}[Demographic IM]                                   |
                                        
|===

== EHR Service

EHR Service API features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|Create EHR                 |{openehr_ehr_api}[EHR Service API]                                         |
|Find EHR                   |                                                                           |
|Get EHR Status             |                                                                           |
|Commit Contribution        |                                                                           |
|Find Compositions          |                                                                           |
|Get Composition by id      |                                                                           |
|Get Composition by time    |                                                                           |
|Get Composition by version |                                                                           |
|===

== TDD API

TDD API features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|Commit TDD                 |                                                                           |
|===

== AQL Support

AQL features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|AQL                        |{openehr_query_aql}[AQL]                                                   |
|===

== Security and Privacy

Security and Privacy features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|Non-identified EHRs        |{openehr_overview}#_overview_4[EHR/Demographic separation]                 |
|Signing                    |{openehr_rm_common}#_digital_signature[Common IM - Digital Signature]      |
|===

== REST APIs

EHR REST API features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|xxx                        |{openehr_ehr_rest_api}[EHR REST API]                                       |
|===


== Integrated Terminology Service

Integrated Terminology features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|AQL query with terminology |                                                                           |
|===

== EHR Dump/Load

EHR Dump/Load features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|xxx                        |                                                                           |
|===

== EHR Synchronisation

EHR Synchronisation features:

[cols="1,3,3", options="header"]
|===
|Feature                    |Specification                                                              |Tested by

|EHR Extract                |{openehr_rm_ehr_extract}[EHR Extract]                                      |
|===


